name: Maven Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Build
        working-directory: jPrime
        run: mvn -B clean package -Drevision=${GITHUB_REF_NAME#v}

      - name: Deploy to GitHub Packages
        working-directory: jPrime
        run: mvn -B deploy -s ${{ github.workspace }}/settings.xml -Drevision=${GITHUB_REF_NAME#v}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
